//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorolaAlpha1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int id { get; set; }
        public System.DateTime fechaexistencia { get; set; }
        public string rotaciones { get; set; }
        public string rendimientowork { get; set; }
        public int id_cliente { get; set; }
        public int id_especies { get; set; }
        public int id_usuario { get; set; }
        public int id_registroentrada { get; set; }
        public int id_registrosalida { get; set; }
    
        public virtual especies especies { get; set; }
        public virtual registroentrada registroentrada { get; set; }
        public virtual registrosalida registrosalida { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
    }
}
